;   .                                                         .   ;
; --+---------------------------------------------------------+-- ;
;   .    Code by: yasserbdj96                                 .   ;
;   .    Email: yasser.bdj96@gmail.com                        .   ;
;   .    GitHub: github.com/yasserbdj96                       .   ;
;   .    Sponsor: github.com/sponsors/yasserbdj96             .   ;
;   .    BTC: bc1q2dks8w8uurca5xmfwv4jwl7upehyjjakr3xga9      .   ;
;   .                                                         .   ;
;   .    All posts with #yasserbdj96                          .   ;
;   .    All views are my own.                                .   ;
; --+---------------------------------------------------------+-- ;
;   .                                                         .   ;

; START{
;[Settings] 
; Default Python path (Windows example)
; Example: C:\Users\[YOUR_USERNAME]\AppData\Local\Programs\Python\[PYTHON_VERSION]\python.exe
; If Python is installed on the system path, you can use 'python' directly.

python_default_path=python

;}END.
