name: APT Repository Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Set up APT repository
      run: |
        REPO_DIR=""      # Replace with the path to your repository
        REPO_NAME="hiphp"                   # Replace with your repository name
        DEB_FILE="./hiphp.deb"       # Replace with the path to your .deb file

        #cd "$REPO_DIR"

        git checkout --orphan gh-pages
        git rm -rf .

        cp "$DEB_FILE" .

        dpkg-scanpackages . /dev/null > Packages
        gzip -k -f Packages

        git add .
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git commit -m "Add hiphp package"
        git push origin gh-pages

        echo "Your APT repository is now hosted on GitHub Pages at:"
        echo "https://$GITHUB_REPOSITORY_OWNER.github.io/$REPO_NAME/"
      
