name: APT Repository Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Set up APT repository
      run: |
        REPO_NAME="hiphp"                   # Replace with your repository name
        DEB_FILE="hiphp.deb"                # Assuming hiphp.deb is in the root directory

        cd $GITHUB_WORKSPACE

        git checkout --orphan gh-pages
        git rm -rf .

        mv "$DEB_FILE" hiphp.deb

        dpkg-scanpackages . /dev/null > Packages
        gzip -k -f Packages

        git add .
        git commit -m "Add hiphp package"
        git push origin gh-pages

        echo "Your APT repository is now hosted on GitHub Pages at:"
        echo "https://$GITHUB_REPOSITORY_OWNER.github.io/$REPO_NAME/"
